baseURL = 'https://budaklembur.pages.dev'
languageCode = 'id'
title = 'Budak Lembur Blog'
theme = 'budaklembur-theme'

[params]
  siteName = "Budak Lembur"
  description = "Sarana berbagi informasi dan tempat menyimpan hasil googling saya, mungkin suatu saat akan diperlukan kembali."
  heroImage = "/images/profil.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "Produk"
    url = "/produk/"
    weight = 30
  [[menu.main]]
    name = "Tentang"
    url = "/tentang/"
    weight = 40
  [[menu.main]]
    name = "Kontak"
    url = "/kontak/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"